outputFormats:
  Team:
    path: team
    mediaType: text/html
    isHTML: true
    permalinkable: true
    notAlternative: true

  Project:
    path: project
    mediaType: text/html
    isHTML: true
    permalinkable: true
    notAlternative: true

  Sponsors:
    path: sponsors
    mediaType: text/html
    isHTML: true
    permalinkable: true
    notAlternative: true

  Join Us:
    path: join-us
    mediaType: text/html
    isHTML: true
    permalinkable: true
    notAlternative: true

module:
  imports:
    - path: github.com/UtkarshVerma/hugo-modules/svg-icon-system
    - path: github.com/UtkarshVerma/hugo-modules/bootstrap-v5
    - path: github.com/michalsnik/aos
      mounts:
        - source: dist
          target: assets
